# GitHub Action to run unittests

name: Unittest-Runner

# Run workflow at 20:00 on every day-of-week from Monday through Friday.
on:
  schedule:
    # * is a special character in YAML so the string must be quoted
    - cron:  '0 20 * * 1-5'

jobs:
  build:
    name: Run Unit tests on Windows (Python 3.7)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Display Python version
      run:
         python -c "import sys; print(sys.version)"
    - name: Install dependencies
      env:
        PYTHONUTF8: 1
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        pip install codecov
    - name: Run tests
      run:
        coverage run -m unittest discover --verbose
    - name: Run codecov
      run:
        codecov
